src/account/urls.py
from django.urls import path

from account.views import (Battles, Invites, PerformerProfile,
                           SpectatorProfile, UpdateInvite)
from core.views import (CustomerLogin, CustomerLogout, PerformerRegistration,
                        SpectatorRegistration)

app_name = "account"

urlpatterns = [
    path("performer-registration/", PerformerRegistration.as_view(), name="performer-registration"),
    path("spectator-registration/", SpectatorRegistration.as_view(), name="spectator-registration"),
    path("login/", CustomerLogin.as_view(), name="login"),
    path("logout/", CustomerLogout.as_view(), name="logout"),
    path("performer-profile/<int:pk>/", PerformerProfile.as_view(), name="performer-profile"),
    path("spectator-profile/<int:pk>/", SpectatorProfile.as_view(), name="spectator-profile"),
    path("invites/<int:pk>/", Invites.as_view(), name="invites"),
    path("battles/<int:pk>/", Battles.as_view(), name="battles"),
    path("change_time/<int:pk>/", UpdateInvite.as_view(), name="change_time"),
]

src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (BattleCreateView, BattleDeleteView,
                       BattleInvitationCreateView, BattleInvitationDeleteView,
                       BattleInvitationUpdateView, BattleInvitationViewSet,
                       BattleUpdateView, BattleViewSet, BattleVoteCreateView,
                       BattleVoteDeleteView, BattleVoteUpdateView,
                       BattleVoteViewSet, CustomerCreateView,
                       CustomerDeleteView, CustomerGetSet, CustomerUpdateView,
                       CustomerViewSet)

app_name = "api"
router = routers.DefaultRouter()
router.register("customers", CustomerViewSet)
router.register("battles", BattleViewSet, "battles")
router.register("battle-invitation", BattleInvitationViewSet)
router.register("battle-vote", BattleVoteViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Call_Out API",
        default_version="v1",
        description="API for making battle",
        terms_of_service="https://policies.google.com/terms",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("", include(router.urls)),
    path("create-customer/", CustomerCreateView.as_view(), name="create-customer"),
    path("delete-customer/<int:pk>", CustomerDeleteView.as_view(), name="delete-customer"),
    path("update-customer/<int:pk>", CustomerUpdateView.as_view(), name="update-customer"),
    path("get-customer/<int:pk>", CustomerGetSet.as_view(), name="get-customer"),
    path("create-battle/", BattleCreateView.as_view(), name="create-battle"),
    path("delete-battle/<int:pk>", BattleDeleteView.as_view(), name="delete-battle"),
    path("update-battle/<int:pk>", BattleUpdateView.as_view(), name="update-battle"),
    path("create-battle-invitation/", BattleInvitationCreateView.as_view(), name="create-battle-invitation"),
    path("delete-battle-invitation/<int:pk>", BattleInvitationDeleteView.as_view(), name="delete-battle-invitation"),
    path("update-battle-invitation/<int:pk>", BattleInvitationUpdateView.as_view(), name="update-battle-invitation"),
    path("create-battle-vote/", BattleVoteCreateView.as_view(), name="create-battle-vote"),
    path("delete-battle-vote/<int:pk>", BattleVoteDeleteView.as_view(), name="delete-battle-vote"),
    path("update-battle-vote/<int:pk>", BattleVoteUpdateView.as_view(), name="update-battle-vote"),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("redoc"), name="swagger-docs"),
]

src/core/urls.py
from django.urls import path

import core.views
from core.views import IndexView, PerformerList

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("list-performers/", PerformerList.as_view(), name="list-performers"),
    path("generating-performers/<int:count>/", core.views.generating_performers, name="generating-performers"),
    path("generating-invitations/<int:count>/", core.views.generating_invitations, name="generating-invitations"),
    path("generating-battles/<int:count>/", core.views.generating_battles, name="generating-battles"),
]

src/templates/index.html
<!doctype html>
{% load static %}

<link href="{% static 'css/cover.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/mycss.css' %}">

<style>
  .header {
  background-color:  transparent
  color: #fff; /* Text color */
  padding: 15px; /* Add some padding for better visibility */
  height:10px; /* Make the header a flex container */
  justify-content: space-between; /* Align items to the left and right edges */
}

.header .active {
  background-color: #fff; /* White active part */
  color: #222; /* Text color */
  border-radius: 5px; /* Rounded corners for the active part */
  padding: 5px 10px; /* Add some padding to the active part */

}

.header h1 {
  margin: 0; /* Remove default margins */
}

.header ul {
  margin: 0; /* Remove default margins */
  display: flex; /* Make the list a flex container */
}

.header li {
  list-style: none; /* Remove default list styles */
  margin-left: 20px; /* Add some spacing between list items */
}

.flex-container {
  display: flex;


}
.header-container {
  width: 450px;
}

.link_header {
  color: transparent; /* Hides the link text */
  display: inline-block; /* Displays the link as a block element */
  padding: 2px; /* Adds padding to create the white frame around the link */
  border: 1px solid grey; /* Creates the white frame */
  border-color: white;
  border-radius: 1px; /* Rounds the corners of the frame */
  background-color: rgba(72, 72, 72, 0.1); /* Sets the background color to transparent white */
  text-decoration: none; /* Removes the default underline from the link */
  text-align: center;
  height: 50px;
  width: 150px;
    border-top: none;
  border-left: none;
  border-right: none;

}


.link_header:hover {

  border-bottom: 3px solid white;
}

.navbar {
  background-color: rgba(0, 0, 0, 0.5);
  position:fixed;
  top: 0;
  left: 0;
  width: 100%;
  display: flex;
  justify-content: right;
  align-items: center;
  padding: 20px;
  box-sizing: border-box;
  z-index: 99;
  height:10%;
}

.logo {
  color: #fff;
  font-size: 24px;
  font-weight: bold;
  text-decoration: none;
}

.nav-links {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
}

.nav-links li {
  margin: 0 10px;
}

.nav-links li a {
  color: #fff;
  font-size: 18px;
  text-decoration: none;
}

.nav-links li a:hover {
  border-bottom: 2px solid #fff;
}



.link-button {
  display: inline-block;
  text-decoration: none;
  padding: 10px 20px;
  margin: 10px;
  color: #fff;
  border: 2px solid #fff;
  border-radius: 8px;
  transition: all 0.3s ease;
}

.link-button:hover {
  background-color: #fff;
  color: #333;
}

.link-button:active {
  background-color: #333;
  color: #fff;
}


.circle-img {
  border-radius: 50%;
}

.dropdown {
  position: fixed;
  display: block;
  left:85%;
}

.dropdown-content {
  display: none;
  position: relative;

  min-width: 100px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  padding: 12px 16px;
  z-index: 1;
  text-align:center;
  left:-25px
}

.dropdown:hover .dropdown-content {
  text-align:center;
  display: block;
  background-color:transparent;
  border-left: 2px solid white;
  border-right: 2px solid white;
}

.dropdown-link {
    color:white;
     font-size: 18px;


}
.dropdown-link:hover {
    background-color:white;
    border: 1px solid #fff;
    color:black;
}

</style>


<header class="header">

  <div class="flex-container">




                <a style="color:#D0D0D0;position:fixed;left:70%" class="link_header" aria-current="page" href="{% url 'core:index' %}"><h2>Home</h2></a>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
                 {% if user.is_authenticated %}

                      {% if not user.photo %}
                      <div class="dropdown"><img src="{% static 'auth/lock2.jpg' %}" alt="mdo" width="62" height="52" class="rounded-circle" style="top:3px;"><br>&nbsp&nbsp&nbsp&nbsp&nbsp{{user.nickname}}&nbsp &nbsp &nbsp &nbsp &nbsp
                      {% else %}
                      <div class="dropdown"><img src={{user.photo.url}} alt="mdo" width="auto" height="72" class="circle-img"><br>&nbsp&nbsp&nbsp&nbsp&nbsp &nbsp &nbsp &nbsp &nbsp
                      {% endif %}
                    <div class="dropdown-content">
                        <a class="dropdown-link"  href="{% url 'account:logout' %}">Logout</a><br><br>
                     {% if user.user_type == 'performer' %}
                        <a class="dropdown-link"  href="{% url 'account:performer-profile' user.pk %}" >Profile</a> <br><br></div>
                         {% endif %}
                         {% if user.user_type == 'spectator' %}
                         <a class="dropdown-link"  href="{% url 'account:spectator-profile' user.pk %}" >Profile</a><br><br></div>
                         {% endif %}

                        {% else %}
                   <a style="color:#E53D00;position:fixed;left:85%;" class="link_header" aria-current="page" href="{% url 'account:login' %}"><h3>Sign up</h3></a>&nbsp &nbsp &nbsp &nbsp

                    {% endif %}
                      </div>



    </div>

</header>

<head>
    <meta charset="UTF-8">
    <title>Callout</title>
</head>

{% block content %}
<body background="{% static 'images/5.jpg' %}">

    <a class="link-button" href="{% url 'core:list-performers' %}" style="position: relative;top: 415px; left: 970px;font-family: Serif, time-new-roman;"><h3>SHOW ALL PERFORMERS</h3></a>

</body>
{% endblock %}
</html>

src/templates/stream.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stream</title>
</head>
<body>
        {% if user.is_authenticated %}
        {{user.email}}
        {% endif %}

      <h1>Room: {{ room_name }}</h1>

    <div id="videos"></div>

    <script src="https://cdn.jsdelivr.net/npm/simplewebrtc@latest/out/simplewebrtc.bundle.js"></script>
    <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
    <script>
        var webrtc = new SimpleWebRTC({
            localVideoEl: 'videos',
            remoteVideosEl: '',
            autoRequestMedia: true,
            debug: false,
            detectSpeakingEvents: true,
            autoAdjustMic: false
        });

        webrtc.on('readyToCall', function () {
            webrtc.joinRoom('{{ room_name }}');
        });
    </script>
</body>
</html>