src/account/urls.py
from django.urls import path

from account.views import (Battles, Invites, PerformerProfile,
                           SpectatorProfile, UpdateInvite)
from core.views import (CustomerLogin, CustomerLogout, PerformerRegistration,
                        SpectatorRegistration)

app_name = "account"

urlpatterns = [
    path("performer-registration/", PerformerRegistration.as_view(), name="performer-registration"),
    path("spectator-registration/", SpectatorRegistration.as_view(), name="spectator-registration"),
    path("login/", CustomerLogin.as_view(), name="login"),
    path("logout/", CustomerLogout.as_view(), name="logout"),
    path("performer-profile/<int:pk>/", PerformerProfile.as_view(), name="performer-profile"),
    path("spectator-profile/<int:pk>/", SpectatorProfile.as_view(), name="spectator-profile"),
    path("invites/<int:pk>/", Invites.as_view(), name="invites"),
    path("battles/<int:pk>/", Battles.as_view(), name="battles"),
    path("change_time/<int:pk>/", UpdateInvite.as_view(), name="change_time"),
]

src/api/urls.py
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions, routers

from api.views import (BattleCreateView, BattleDeleteView,
                       BattleInvitationCreateView, BattleInvitationDeleteView,
                       BattleInvitationUpdateView, BattleInvitationViewSet,
                       BattleUpdateView, BattleViewSet, BattleVoteCreateView,
                       BattleVoteDeleteView, BattleVoteUpdateView,
                       BattleVoteViewSet, CustomerCreateView,
                       CustomerDeleteView, CustomerGetSet, CustomerUpdateView,
                       CustomerViewSet)

app_name = "api"
router = routers.DefaultRouter()
router.register("customers", CustomerViewSet)
router.register("battles", BattleViewSet, "battles")
router.register("battle-invitation", BattleInvitationViewSet)
router.register("battle-vote", BattleVoteViewSet)

schema_view = get_schema_view(
    openapi.Info(
        title="Call_Out API",
        default_version="v1",
        description="API for making battle",
        terms_of_service="https://policies.google.com/terms",
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    path("", include(router.urls)),
    path("create-customer/", CustomerCreateView.as_view(), name="create-customer"),
    path("delete-customer/<int:pk>", CustomerDeleteView.as_view(), name="delete-customer"),
    path("update-customer/<int:pk>", CustomerUpdateView.as_view(), name="update-customer"),
    path("get-customer/<int:pk>", CustomerGetSet.as_view(), name="get-customer"),
    path("create-battle/", BattleCreateView.as_view(), name="create-battle"),
    path("delete-battle/<int:pk>", BattleDeleteView.as_view(), name="delete-battle"),
    path("update-battle/<int:pk>", BattleUpdateView.as_view(), name="update-battle"),
    path("create-battle-invitation/", BattleInvitationCreateView.as_view(), name="create-battle-invitation"),
    path("delete-battle-invitation/<int:pk>", BattleInvitationDeleteView.as_view(), name="delete-battle-invitation"),
    path("update-battle-invitation/<int:pk>", BattleInvitationUpdateView.as_view(), name="update-battle-invitation"),
    path("create-battle-vote/", BattleVoteCreateView.as_view(), name="create-battle-vote"),
    path("delete-battle-vote/<int:pk>", BattleVoteDeleteView.as_view(), name="delete-battle-vote"),
    path("update-battle-vote/<int:pk>", BattleVoteUpdateView.as_view(), name="update-battle-vote"),
    path("auth/", include("djoser.urls.jwt")),
    path("docs/", schema_view.with_ui("redoc"), name="swagger-docs"),
]

src/callout/urls.py
from django.urls import path, re_path

from callout.views import BattleRoom, Invitation

app_name = "callout"

urlpatterns = [
    path("invite/<int:pk>/", Invitation.as_view(), name="invite"),
    path("battle-room/<int:pk>/,", BattleRoom.as_view(), name="battle-room"),
]

src/templates/users/battles.html
 {% extends "index.html" %}

{% block content %}
 {% load static %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/mycss.css' %}" >
 <body background="{% static 'images/5_without_text.jpg' %}" style="background-repeat:no-repeat;background-attachment: fixed;">
<div class="my-container">
<div class="centered-object">

 {% for battle in user.battles.all %}

    <h2><a class="text-list" href="{% url 'callout:battle-room' battle.pk %}">{{battle.who_made_callout.nickname}} vs {{battle.who_accepted_callout.nickname}} <br>{{battle.start_time}}</a></h2>
 {% endfor %}
</div>
</div>
 {% endblock %}

src/templates/users/change_time.html
{% extends "index.html" %}

{% block content %}
    <div>
        <form method = 'POST' style="width:25em; align-content:center;margin:auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <button type = 'submit' value ='Login' class="btn btn-primary">Send</button>
        </form><br><br>
    </div>

    {% if changed_time %}
    {{changed_time}}
    {% endif %}
{% endblock %}

src/templates/users/invites.html
 {% extends "index.html" %}

{% block content %}

    {%  for invite in user.invitations.all %}
        {% if user.nickname == invite.sender.nickname %}
        You invite {{invite.performer.nickname}}<br>
        {% else %}
        {{invite.sender.nickname}} invites you <br>
        {% endif %}
        {{invite.music_style}} <br>

        {{invite.accepted_performer}} {{invite.accepted_sender}}


        {% if user.nickname == invite.sender.nickname and invite.accepted_sender %}
        <a>{{invite.date_and_time}}</a> <br><br>
        {% elif user.nickname == invite.performer.nickname and invite.accepted_performer %}
        <a>{{invite.date_and_time}}</a> <br><br>
        {% else %}
        <a>Changed   {{invite.date_and_time}}</a> <br><br>
               <form class="form" method="POST">
     {% csrf_token %}
        <input type="hidden" value={{invite.pk}} name="accept_invitation">
        <button type = 'submit' value ='Submit' class="btn btn-success">Accept</button>
            </form>

        <form class="form" method="POST">
     {% csrf_token %}
        <input type="hidden" value={{invite.pk}} name="change_time">
        <button type = 'submit' value ='Submit' class="btn btn-warning">Change time</button>
            </form>

        {% endif %}
       {# {% else %} #}
       {# <a>{{invite.date_and_time}}</a> <br><br> #}

      {#  {% endif %} #}





           <form class="form" method="POST">
     {% csrf_token %}
        <input type="hidden" value={{invite.pk}} name="canсel_invitation">
        <button type = 'submit' value ='Submit' class="btn btn-danger">Сancel</button>
            </form>


        <br> <br> <br>

    {% endfor %}


    {{invitation_instance}}


 {% endblock %}

src/templates/users/list_performers.html
 {% extends "index.html" %}

{% block content %}
{% load static %}
 <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
 <body style="background-repeat:no-repeat;background-attachment: fixed;">
<div class="my-container">
<div class="centered-object">
    <br><br><br>
 <form xmlns="http://www.w3.org/1999/html">
    <input type='text' id='search_text' name = 'search_text'>
    <button type = 'submit' value ='Submit'>Search</button> <br><br>
  </form>



  {% for performer in object_list %}
        {% if performer.user_type == 'performer' and user.pk != performer.pk %}
       {% if performer.photo %}
        <img src={{performer.photo.url}} height="auto" width="200px" class="circle-img"><br>
        {% else %}
        <img src={% static 'images/No-photo.png' %} height="auto" width="200px" class="circle-img">
      {% endif %}


        <h2><a class="text-list" href="{% url 'account:performer-profile' performer.pk %}">{{performer.nickname}}</a></h2>
        <a class="text-list" style="position:relative;top:-15px;">({{performer.dance_style}})</a>
        <br>



            {% if performer.email not in all_users %}
            <form class="form" method="POST">
              {% csrf_token %}
            <input type="hidden" value="{{performer.pk}}" name="performer_pk">
            <button type = 'submit' value ='Submit' class="btn btn-outline-success">Subscribe</button>
            </form>

            {% else %}
            <form class="form" method="POST">
              {% csrf_token %}
            <input type="hidden" value="{{performer.pk}}" name="performer_unsubscribe">
            <button type = 'submit' value ='Submit' class="btn btn-outline-warning">Unsubscribe</button>
            </form>
            {% endif %}




        {% if user.user_type == 'performer' %}

        {% if performer.pk not in all_invitations %}
        <form class="form" method="POST">
              {% csrf_token %}
            <input type="hidden" value="{{performer.pk}}" name="callout">
            <button type = 'submit' value ='Submit' class="btn btn-outline-danger">Call out</button>
            </form>
           {% else %}
           <a>Already Invited</a>

        {% endif %} <br>

        {% endif %}
        <br><br><br>
    {% endif %}
    {% endfor %}
  </tbody>

</table>
    </div>
</div>
 </body>
{% endblock %}

src/templates/users/performer_profile.html
 {% extends "index.html" %}

{% block content %}
{% load static %}
 <link rel="stylesheet" href="{% static 'css/cover.css' %}">
<br><br><br><br>
  <body style="background-repeat:no-repeat;background-attachment: fixed;">
<div class="my-container">
<div class="centered-object">
 <a>Performer Profile</a><br>

 {% if object.photo %}

  <img src={{object.photo.url}} height="200" width="auto" class="circle-img">
  <br><br>
 {{ object.first_name }} &nbsp {{ object.last_name }}
 {% endif %}
 <br><br><br>
 <a class="link-button" aria-current="page" href="{% url 'account:invites' object.pk %}">Invites</a>
 <a class="link-button" aria-current="page" href="{% url 'account:battles' object.pk %}">Battles</a>
 {% if object.promo_video %}
<video width="800"  controls>
    <source src={{object.promo_video.url}} type="video/mp4" />
</video>
 {% endif %}
<br><br>
 <h2>Subsctiptions</h2>
 {% for subscibtion in object.subscribtions.all %}
  {% if subscibtion.photo %}
  {{subscibtion.photo.url}}
   {% else %}
  <img src="{% static 'auth/lock.png' %}" alt="mdo" width="50" height="50" style="border-radius: 50%;">
  {% endif %}
 <a href="{% url 'account:performer-profile' subscibtion.pk %}">{{subscibtion.nickname}}</a>
  <br>
 {% endfor %}
</div>
</div>
  </body>
{% endblock %}

src/templates/users/spectator_profile.html
 {% extends "index.html" %}

{% block content %}

 <a>Spectator Profile</a>

{% endblock %}